jobs:
- job: VS_Latest

  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    inputs:
      version: 9.0.100-rc.2.24474.11
      includePreviewVersions: true

  - task: nventiveCanaryUpdater@5
    displayName: 'Canary Update'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/canaries')
    inputs:
      solution: Quoter.sln
      branchToMerge: uno
      summaryFile: '$(Build.ArtifactStagingDirectory)/Canary.md'
      resultFile: '$(Build.ArtifactStagingDirectory)/result.json'
      nugetUpdaterVersion: 2.0.6
      packageAuthor: nventive

  - task: GitVersion@5
    inputs:
      useConfigFile: true
      configFilePath: gitversion.yml

  - script: |
      dotnet publish $(build.sourcesdirectory)/src/uno/RoslynQuoter/RoslynQuoterApp.csproj "/p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION" 

    env:
      GITVERSION_FullSemVer: $(GITVERSION_FullSemVer)
    displayName: 'Build'
  
  - task: PublishBuildArtifacts@1
    displayName: Publish Package Artifacts
    inputs:
      pathToPublish: $(build.sourcesdirectory)/src/uno/RoslynQuoter.Wasm/bin/Release/net9.0/publish/wwwroot
      artifactType: container
      artifactName: RoslynQuoter-Wasm
